# -*- coding: utf-8 -*-
"""user_funnel_analysis.ipynb

Automatically generated by Colaboratory.

# **1. Import libraries and data**
"""

# Import libraries
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio

# Import data
data = pd.read_csv("user_data.csv")

"""# **2. Display the first 5 rows of data**"""

# Display the first 5 rows of data
print("First 5 rows of data:")
display(data.head())

"""# **3. Dataset information**"""

# Dataset information
num_rows, num_cols = data.shape

# Print the number of rows and columns
print("Dataset Information:")
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_cols}")

"""# **4. Count the number of users in each stage of the funnel**"""

# Count the number of users in each stage of the funnel
print(data["stage"].value_counts())

"""# **5. Define the funnel stages**"""

# Define the funnel stages
funnel_stages = ['homepage', 'product_page', 'cart', 'checkout', 'purchase']

"""# **6. Calculate the number of users and conversions for each stage**"""

# Calculate the number of users and conversions for each stage
num_users = []
num_conversions = []

for stage in funnel_stages:
    stage_users = data[data['stage'] == stage]
    num_users.append(len(stage_users))
    num_conversions.append(stage_users['conversion'].sum())

"""# **7. Create a funnel chart to visualize the analysis**"""

# Create a funnel chart to visualize the analysis
fig = go.Figure(go.Funnel(
    y=funnel_stages,
    x=num_users,
    textposition='inside',
    textinfo='value',
    name='Users'
))

fig.add_trace(go.Funnel(
    y=funnel_stages,
    x=num_conversions,
    textposition='inside',
    textinfo='value',
    name='Conversions'
))

fig.update_layout(
    title='Funnel Analysis',
    funnelmode='stack'
)

# Display the chart and explanations
display(fig)