!pip install matplotlib
!pip install pandas
!pip install numpy

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Define the data to be visualized
menu_items = ["pancakes", "waffles", "burger", "home fries", "coffee", "espresso", "tea", "mimosa", "orange juice", "juice"]
menu_prices = [7.5, 9.0, 11.0, 4.5, 1.5, 3.0, 1.0, 10.5, 3.5, 2.5]
total_revenue = [418.50, 31.00]

# Define the subplots
fig, (ax1, ax2, ax3) = plt.subplots(nrows=1, ncols=3, figsize=(18,6))

# Plot the revenue generated by each franchise
franchise_names = ["Basta Fazoolin' with my Heart", "Take a' Arepa"]
revenues = pd.Series(total_revenue, index=franchise_names)
revenues.plot(kind="bar", ax=ax1, color=["#FFC300", "#C70039"])
ax1.set_title("Total Revenue by Franchise")
ax1.set_xlabel("Franchise")
ax1.set_ylabel("Total Revenue ($)")
ax1.tick_params(axis="x", labelrotation=0)

# Plot the most popular menu items
popularity = pd.Series(menu_prices, index=menu_items).sort_values(ascending=False)[:5]
popularity.plot(kind="barh", ax=ax2, color=["#FFC300", "#FFC300", "#FFC300", "#FFC300", "#C70039"])
ax2.set_title("Most Popular Menu Items")
ax2.set_xlabel("Price ($)")
ax2.set_ylabel("Menu Item")

# Plot the total revenue by menu item
total_sales = np.multiply(menu_prices, np.random.randint(50, 100, len(menu_items)))
total_sales_by_item = pd.Series(total_sales, index=menu_items)
total_sales_by_item.plot(kind="bar", ax=ax3, color="#C70039")
ax3.set_title("Total Revenue by Menu Item")
ax3.set_xlabel("Menu Item")
ax3.set_ylabel("Total Revenue ($)")
ax3.tick_params(axis="x", labelrotation=45)

# Add a subtitle
fig.suptitle("Restaurant Data Visualization", fontsize=20)

# Add a footer with source and date
fig.text(0.1, 0.01, "Source: Restaurant Sales Data, March 2023", fontsize=10)

# Adjust spacing between subplots
fig.tight_layout(pad=3.0)

# Show the plot
plt.show()
